/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CurriculumTopic = IDL.Record({
  'topic' : IDL.Text,
  'subject' : IDL.Text,
});
export const TestQuestion = IDL.Record({
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const TestScore = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
  'grade' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTestScore' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurriculum' : IDL.Func([IDL.Text], [IDL.Vec(CurriculumTopic)], ['query']),
  'getTestQuestions' : IDL.Func([IDL.Text], [IDL.Vec(TestQuestion)], ['query']),
  'getTestScores' : IDL.Func([], [IDL.Vec(TestScore)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CurriculumTopic = IDL.Record({
    'topic' : IDL.Text,
    'subject' : IDL.Text,
  });
  const TestQuestion = IDL.Record({
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const TestScore = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
    'grade' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTestScore' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurriculum' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CurriculumTopic)],
        ['query'],
      ),
    'getTestQuestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TestQuestion)],
        ['query'],
      ),
    'getTestScores' : IDL.Func([], [IDL.Vec(TestScore)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };