/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord { 'status' : string, 'date' : string }
export interface CurriculumTopic { 'topic' : string, 'subject' : string }
export interface TestQuestion {
  'question' : string,
  'subject' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface TestScore {
  'totalMarks' : bigint,
  'subject' : string,
  'score' : bigint,
  'grade' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestScore' : ActorMethod<[string, bigint, bigint, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurriculum' : ActorMethod<[string], Array<CurriculumTopic>>,
  'getTestQuestions' : ActorMethod<[string], Array<TestQuestion>>,
  'getTestScores' : ActorMethod<[], Array<TestScore>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];